const sequelize = require("../../db");
const { DataTypes } = require("sequelize");
const { WeekType } = require("./WeekType");
const Pair = sequelize.define("Pair", {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  weekday_number: {
    type: DataTypes.INTEGER,
    allowNull: false,
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  start: {
    type: DataTypes.TIME,
    allowNull: false,
  },
  end: {
    type: DataTypes.TIME,
    allowNull: false,
  },
  break_start: {
    type: DataTypes.TIME,
    allowNull: false,
  },
  break_end: {
    type: DataTypes.TIME,
    allowNull: false,
  },
  week_type_name: {
    type: DataTypes.STRING,
    references: {
      model: WeekType,
      key: "name",
    },
    allowNull: false,
  },
});
const nameOfUpperWeek = 'Верхняя неделя';
const nameOfLowerWeek = 'Нижняя неделя';
 
const defaultData = [
      //Понедельник
  {
    weekday_number: 1,
    name: "1 пара",
    start: "08:30",
    end: "09:15",
    break_start: "09:20",
    break_end: "10:05",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 1,
    name: "1 пара",
    start: "08:30",
    end: "09:15",
    break_start: "09:20",
    break_end: "10:05",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 1,
    name: "2 пара",
    start: "10:25",
    end: "11:10",
    break_start: "11:15",
    break_end: "12:00",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 1,
    name: "2 пара",
    start: "10:25",
    end: "11:10",
    break_start: "11:15",
    break_end: "12:00",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 1,
    name: "3 пара",
    start: "12:30",
    end: "13:15",
    break_start: "13:20",
    break_end: "14:05",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 1,
    name: "3 пара",
    start: "12:30",
    end: "13:15",
    break_start: "13:20",
    break_end: "14:05",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 1,
    name: "4 пара",
    start: "14:20",
    end: "15:05",
    break_start: "15:10",
    break_end: "15:55",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 1,
    name: "4 пара",
    start: "14:20",
    end: "15:05",
    break_start: "15:10",
    break_end: "15:55",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 1,
    name: "5 пара",
    start: "16:05",
    end: "16:50",
    break_start: "16:55",
    break_end: "17:40",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 1,
    name: "5 пара",
    start: "16:05",
    end: "16:50",
    break_start: "16:55",
    break_end: "17:40",
    week_type_name: nameOfLowerWeek,
  },
  //Вторник
  {
    weekday_number: 2,
    name: "1 пара",
    start: "08:30",
    end: "09:15",
    break_start: "09:20",
    break_end: "10:05",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 2,
    name: "1 пара",
    start: "08:30",
    end: "09:15",
    break_start: "09:20",
    break_end: "10:05",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 2,
    name: "2 пара",
    start: "10:25",
    end: "11:10",
    break_start: "11:15",
    break_end: "12:00",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 2,
    name: "2 пара",
    start: "10:25",
    end: "11:10",
    break_start: "11:15",
    break_end: "12:00",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 2,
    name: "3 пара",
    start: "12:30",
    end: "13:15",
    break_start: "13:20",
    break_end: "14:05",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 2,
    name: "3 пара",
    start: "12:30",
    end: "13:15",
    break_start: "13:20",
    break_end: "14:05",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 2,
    name: "4 пара",
    start: "14:20",
    end: "15:05",
    break_start: "15:10",
    break_end: "15:55",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 2,
    name: "4 пара",
    start: "14:20",
    end: "15:05",
    break_start: "15:10",
    break_end: "15:55",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 2,
    name: "5 пара",
    start: "16:05",
    end: "16:50",
    break_start: "16:55",
    break_end: "17:40",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 2,
    name: "5 пара",
    start: "16:05",
    end: "16:50",
    break_start: "16:55",
    break_end: "17:40",
    week_type_name: nameOfLowerWeek,
  },
  //Среда
  {
    weekday_number: 3,
    name: "1 пара",
    start: "08:30",
    end: "09:15",
    break_start: "09:20",
    break_end: "10:05",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 3,
    name: "1 пара",
    start: "08:30",
    end: "09:15",
    break_start: "09:20",
    break_end: "10:05",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 3,
    name: "2 пара",
    start: "10:25",
    end: "11:10",
    break_start: "11:15",
    break_end: "12:00",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 3,
    name: "2 пара",
    start: "10:25",
    end: "11:10",
    break_start: "11:15",
    break_end: "12:00",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 3,
    name: "3 пара",
    start: "12:30",
    end: "13:15",
    break_start: "13:20",
    break_end: "14:05",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 3,
    name: "3 пара",
    start: "12:30",
    end: "13:15",
    break_start: "13:20",
    break_end: "14:05",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 3,
    name: "4 пара",
    start: "14:20",
    end: "15:05",
    break_start: "15:10",
    break_end: "15:55",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 3,
    name: "4 пара",
    start: "14:20",
    end: "15:05",
    break_start: "15:10",
    break_end: "15:55",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 3,
    name: "5 пара",
    start: "16:05",
    end: "16:50",
    break_start: "16:55",
    break_end: "17:40",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 3,
    name: "5 пара",
    start: "16:05",
    end: "16:50",
    break_start: "16:55",
    break_end: "17:40",
    week_type_name: nameOfLowerWeek,
  },
  //Четверг
  {
    weekday_number: 4,
    name: "1 пара",
    start: "08:30",
    end: "09:15",
    break_start: "09:20",
    break_end: "10:05",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 4,
    name: "1 пара",
    start: "08:30",
    end: "09:15",
    break_start: "09:20",
    break_end: "10:05",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 4,
    name: "2 пара",
    start: "10:25",
    end: "11:10",
    break_start: "11:15",
    break_end: "12:00",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 4,
    name: "2 пара",
    start: "10:25",
    end: "11:10",
    break_start: "11:15",
    break_end: "12:00",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 4,
    name: "3 пара",
    start: "12:30",
    end: "13:15",
    break_start: "13:20",
    break_end: "14:05",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 4,
    name: "3 пара",
    start: "12:30",
    end: "13:15",
    break_start: "13:20",
    break_end: "14:05",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 4,
    name: "4 пара",
    start: "14:20",
    end: "15:05",
    break_start: "15:10",
    break_end: "15:55",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 4,
    name: "4 пара",
    start: "14:20",
    end: "15:05",
    break_start: "15:10",
    break_end: "15:55",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 4,
    name: "5 пара",
    start: "16:05",
    end: "16:50",
    break_start: "16:55",
    break_end: "17:40",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 4,
    name: "5 пара",
    start: "16:05",
    end: "16:50",
    break_start: "16:55",
    break_end: "17:40",
    week_type_name: nameOfLowerWeek,
  },
  //Пятница
  {
    weekday_number: 5,
    name: "1 пара",
    start: "08:30",
    end: "09:15",
    break_start: "09:20",
    break_end: "10:05",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 5,
    name: "1 пара",
    start: "08:30",
    end: "09:15",
    break_start: "09:20",
    break_end: "10:05",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 5,
    name: "2 пара",
    start: "10:25",
    end: "11:10",
    break_start: "11:15",
    break_end: "12:00",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 5,
    name: "2 пара",
    start: "10:25",
    end: "11:10",
    break_start: "11:15",
    break_end: "12:00",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 5,
    name: "3 пара",
    start: "12:30",
    end: "13:15",
    break_start: "13:20",
    break_end: "14:05",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 5,
    name: "3 пара",
    start: "12:30",
    end: "13:15",
    break_start: "13:20",
    break_end: "14:05",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 5,
    name: "4 пара",
    start: "14:20",
    end: "15:05",
    break_start: "15:10",
    break_end: "15:55",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 5,
    name: "4 пара",
    start: "14:20",
    end: "15:05",
    break_start: "15:10",
    break_end: "15:55",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 5,
    name: "5 пара",
    start: "16:05",
    end: "16:50",
    break_start: "16:55",
    break_end: "17:40",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 5,
    name: "5 пара",
    start: "16:05",
    end: "16:50",
    break_start: "16:55",
    break_end: "17:40",
    week_type_name: nameOfLowerWeek,
  },
  //Субота
  {
    weekday_number: 6,
    name: "1 пара",
    start: "08:30",
    end: "09:15",
    break_start: "09:20",
    break_end: "10:05",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 6,
    name: "1 пара",
    start: "08:30",
    end: "09:15",
    break_start: "09:20",
    break_end: "10:05",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 6,
    name: "2 пара",
    start: "10:25",
    end: "11:10",
    break_start: "11:15",
    break_end: "12:00",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 6,
    name: "2 пара",
    start: "10:25",
    end: "11:10",
    break_start: "11:15",
    break_end: "12:00",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 6,
    name: "3 пара",
    start: "12:30",
    end: "13:15",
    break_start: "13:20",
    break_end: "14:05",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 6,
    name: "3 пара",
    start: "12:30",
    end: "13:15",
    break_start: "13:20",
    break_end: "14:05",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 6,
    name: "4 пара",
    start: "14:20",
    end: "15:05",
    break_start: "15:10",
    break_end: "15:55",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 6,
    name: "4 пара",
    start: "14:20",
    end: "15:05",
    break_start: "15:10",
    break_end: "15:55",
    week_type_name: nameOfLowerWeek,
  },
  {
    weekday_number: 6,
    name: "5 пара",
    start: "16:05",
    end: "16:50",
    break_start: "16:55",
    break_end: "17:40",
    week_type_name: nameOfUpperWeek,
  },
  {
    weekday_number: 6,
    name: "5 пара",
    start: "16:05",
    end: "16:50",
    break_start: "16:55",
    break_end: "17:40",
    week_type_name: nameOfLowerWeek,
  },
];

// Функция для инициализации данных
const initializePair = async () => {
  for (const data of defaultData) {
    await Pair.create(data);
  }
};

// Экспортируйте модель и инициализацию
module.exports = { Pair, initializePair };
